# Generated by Django 5.1.6 on 2025-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("grade", models.IntegerField()),
                ("section", models.CharField(max_length=1)),
                ("attendance", models.FloatField()),
                ("test_score", models.FloatField()),
                ("homework_score", models.FloatField()),
                ("final_score", models.FloatField()),
            ],
        ),
    ]
