# Generated by Django 5.1.6 on 2025-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="final_score",
            new_name="final_exam",
        ),
        migrations.AddField(
            model_name="student",
            name="aggregate",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
