# Generated by Django 5.1.6 on 2025-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_final_score_student_final_exam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
