# Generated by Django 5.1.6 on 2025-04-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_homework"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="created_at",
        ),
    ]
