# Generated by Django 5.1.6 on 2025-04-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_homework_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="final_exam",
        ),
        migrations.RemoveField(
            model_name="student",
            name="homework_score",
        ),
        migrations.RemoveField(
            model_name="student",
            name="test_score",
        ),
    ]
