# Generated by Django 5.1.6 on 2025-04-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_student_final_exam_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="aggregate",
            new_name="final_aggregate",
        ),
    ]
