# Generated by Django 5.1.6 on 2025-05-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_student_user_teacher_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="myapp.student",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="myapp.teacher",
            ),
        ),
    ]
