# Generated by Django 5.1.6 on 2025-05-01 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_leave_student_alter_leave_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="student",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
        migrations.AlterField(
            model_name="leave",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="myapp.teacher",
            ),
            preserve_default=False,
        ),
    ]
