# Generated by Django 5.1.6 on 2025-05-01 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_remove_leave_student_remove_teacher_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="name",
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
