# Generated by Django 5.1.6 on 2025-05-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_remove_teacher_name_teacher_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
    ]
