# Generated by Django 5.1.6 on 2025-05-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_alter_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_trained", models.DateTimeField(auto_now_add=True)),
                ("subject_name", models.CharField(max_length=100)),
                ("grade", models.IntegerField()),
                ("section", models.CharField(max_length=1)),
                ("intercept", models.FloatField()),
                ("coefficients", models.JSONField()),
                ("r2_score", models.FloatField()),
            ],
        ),
    ]
