# Generated by Django 5.1.6 on 2025-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_modeltraining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeltraining",
            name="grade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
