# Generated by Django 5.1.6 on 2025-05-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_alter_modeltraining_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeltraining",
            name="model_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
