# Generated by Django 5.1.6 on 2025-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_modeltraining_model_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(default="2024", max_length=10),
        ),
    ]
