# Generated by Django 5.1.6 on 2025-05-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_student_academic_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="academic_year",
            field=models.CharField(default="2025", max_length=10),
        ),
    ]
