# Generated by Django 5.1.6 on 2025-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_alter_student_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
