# Generated by Django 5.1.6 on 2025-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_leave_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("routine", models.ImageField(upload_to="daily_routines/")),
            ],
        ),
    ]
