# Generated by Django 5.1.6 on 2025-10-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_remove_dailyroutine_title_dailyroutine_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyroutine",
            name="routine",
            field=models.FileField(upload_to="daily_routines/"),
        ),
    ]
